# This workflow runs with a READ-ONLY GITHUB_TOKEN
# https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

# This action will run a `yarn install` without write access to the repository
# as this can execute potentially unsafe third-party ruby code when installing
# git dependencies.

# The completion of this workflow triggers the `Update Dependabot Yarn PR`
# workflow which has a read-write GITHUB_TOKEN, extracting the changes to
# license files and pushing these to back to the Dependabot PR branch.

name: Build Dependabot Yarn PR
on:
  push:
    branches:
      - "dependabot/npm_and_yarn**"
  pull_request:
    branches:
      - "dependabot/npm_and_yarn/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # IMPORTANT: setting YARN_ENABLE_SCRIPTS=false is critical to ensure that untrusted
    # PRs can't add an npm package and then use that to execute untrusted code in
    # a trusted context. See links at the top of this workflow for further details.
    # See also: https://github.com/yarnpkg/berry/issues/1679#issuecomment-669937860
    env:
      YARN_ENABLE_SCRIPTS: false
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 16.13.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: 'yarn'
      - run: yarn install --mode=update-lockfile
      - run: mkdir ./dependabot-pr
      - name: Save branch ref
        run: echo ${{ github.ref }} | sed 's/refs\/heads\///' > ./dependabot-pr/BRANCH_REF
      - name: Configure git
        run: |
          git config --local user.email "49699333+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      # NOTE: Prefixing/appending commit messages with `[dependabot skip]` allows
      # dependabot to rebase/update the pull request, force-pushing over any changes
      - name: Commit yarn.lock
        run: |
          if [[ $(git status | grep 'yarn.lock') ]]; then
            git add yarn.lock
            git commit -m "[dependabot skip] Fix yarn.lock"
            git format-patch -n HEAD^ --binary --stdout > ./dependabot-pr/changes.patch
          else
            echo "Lock has not changed"
          fi
      # NOTE: Use actions/upload-artifact instead of actions/cache as the
      # workflow triggered on the default branch doesn't have access to caches
      # created on feature branches
      - uses: actions/upload-artifact@v3
        with:
          name: dependabot-pr
          path: dependabot-pr/
