# This will run the full test
#
# dependabot/npm_and_yarn/**
#  - pull requests
#  - pushes

name: Verify

on:
  push:
    branches:
      - "dependabot/npm_and_yarn/**"
  pull_request:
    branches:
      - "dependabot/npm_and_yarn/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.13.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: ESLint
        run: yarn lint

      - name: Build
        run: yarn build
