# This will run the full test
#
# dependabot/npm_and_yarn/**
#  - pull requests
#  - pushes

name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [16.12.0, 16.15.0]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Test
        run: yarn test

      - name: ESLint
        run: yarn lint

      - name: Build
        run: yarn build
