# This will run the full test
#
# dependabot/npm_and_yarn/**
#  - pull requests
#  - pushes

name: Verify

on:
  push:
    branches:
      - "dependabot/npm_and_yarn/**"
  pull_request:
    branches:
      - "dependabot/npm_and_yarn/**"
  workflow_run:
    workflows: ["Update Dependabot Yarn PR"]
    types:
      - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.13.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn type-check

      - name: Test
        run: yarn test

      - run: yarn test:generate-output

      - name: ESLint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test storybook build
        run: yarn storybook:test
